# Pull tomcat latest image from dockerhub
From tomcat:8.0
# Maintainer
MAINTAINER "Janani K"
# copy war file on to container
COPY ./sample.war /usr/local/tomcat/webapps
WORKDIR /usr/local/tomcat/webapps/
RUN jar -xvf /usr/local/tomcat/webapps/sample.war
